"""Regenerate tests/fixtures/council_session_ffa3_v1.json — the FF-A3 SYNTHETIC
Council fixture (ADR-069).

    docker compose exec backend python scripts/make_ffa3_fixture.py          # write
    docker compose exec backend python scripts/make_ffa3_fixture.py --check  # drift

**Synthetic hand-authored Council alternatives prove replay and pipeline
compatibility only — not that an AI selected the primitive from prose.**

What IS real in this fixture:
  * the brief block is composed by the SAME code the live route uses
    (`app.intake.models.summary_block` over the typed intake fixture);
  * every PROMPT is generated by the real prompt builders in
    `app.council.prompts`, so the transcript is byte-for-byte what the
    Council would be sent for this brief on this checkout — and `--check`
    (run by gate_ffa3) fails loudly the day a builder or the schema
    changes, so the fixture can never silently go stale;
  * every Design Spec is validated here against design_spec_v1.json, the
    live registry, the trusted mapper and the primitive's own validate();
  * spec hashes are the canonical replay hashes.

What is NOT real: the RESPONSES are hand-authored; token counts are
len(text) // 4 approximations; no provider was called; the dollar figure
replay recomputes was never spent.
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "council_session_ffa3_v1.json"
INTAKE_PATH = REPO_ROOT / "tests" / "fixtures" / "intake_ffa3_v1.json"
SCHEMA_PATH = REPO_ROOT / "schemas" / "design_spec_v1.json"

NS = uuid.UUID("6f1a3c08-ffa3-4a69-8f08-000000000069")   # id namespace
SESSION_ID = "f5a3e1c8-ffa3-4069-9c08-000000000069"
PROJECT_ID = "7c9e6679-7425-40de-944b-e07fc1f90ae7"
STARTED = "2026-09-09T09:00:00+00:00"
ENDED = "2026-09-09T09:07:30+00:00"
LATENCY_MS = 1000.0

NOTE = (
    "SYNTHETIC hand-authored FF-A3 fixture (ADR-069). Synthetic hand-authored "
    "Council alternatives prove replay and pipeline compatibility only — not "
    "that an AI selected the primitive from prose. Prompts are generated by "
    "the real prompt builders (byte-identical to a live session's prompts on "
    "this checkout); responses are hand-authored; token counts are "
    "len(text)//4 approximations; no provider was called and the dollar "
    "figure replay recomputes was never spent. Regenerate with "
    "scripts/make_ffa3_fixture.py; never hand-edit."
)


def _id(label: str) -> str:
    return str(uuid.uuid5(NS, label))


# ---------------------------------------------------------------------------
# the six hand-authored parameterizations (all 12 scalars + material_id,
# every one stated explicitly — correction 9)
# ---------------------------------------------------------------------------

def _mm(v: float) -> dict:
    return {"value": v, "unit": "mm"}


def _m(v: float) -> dict:
    return {"value": v, "unit": "m"}


def _deg(v: float) -> dict:
    return {"value": v, "unit": "deg"}


#: (provider, alternative_no, seed, concept, parameters-in-spec-vocabulary)
VARIANTS = [
    ("anthropic", 1, 8, "The FF-A2 acceptance lens: one hollow 316L loop, "
     "window right of centre, gentle 20° twist",
     {"height": _m(4.25), "width": _mm(2569), "depth": _mm(900),
      "wall": _mm(6), "twist": _deg(20), "bow": _mm(150), "skew": 0.15,
      "window_width": _mm(1110), "window_height": _mm(1290),
      "window_center_height": 0.485, "waist_height": 0.45,
      "plate_diameter": _mm(600), "material_id": "stainless_316l_sheet"}),
    # NOTE (ADR-069 decision 6): the first-written variants with NEGATIVE
    # twist (-20 / -25 / -35 deg) passed validate() and were REFUSED at
    # build by the kernel's stage checks; these replacements build.
    ("openai", 1, 9, "Same envelope as the acceptance lens, window left of "
     "centre, bow reversed",
     {"height": _m(4.25), "width": _mm(2569), "depth": _mm(900),
      "wall": _mm(6), "twist": _deg(20), "bow": _mm(-150), "skew": -0.15,
      "window_width": _mm(1110), "window_height": _mm(1290),
      "window_center_height": 0.485, "waist_height": 0.45,
      "plate_diameter": _mm(600), "material_id": "stainless_316l_sheet"}),
    ("anthropic", 2, 21, "Taller, narrower loop in 8 mm sheet with a higher "
     "window",
     {"height": _mm(4800), "width": _mm(2700), "depth": _mm(1000),
      "wall": _mm(8), "twist": _deg(20), "bow": _mm(200), "skew": 0.12,
      "window_width": _mm(1200), "window_height": _mm(1400),
      "window_center_height": 0.5, "waist_height": 0.5,
      "plate_diameter": _mm(700), "material_id": "stainless_316l_sheet"}),
    ("openai", 2, 22, "Tall loop, wider envelope, bow reversed",
     {"height": _mm(4800), "width": _mm(2900), "depth": _mm(1000),
      "wall": _mm(8), "twist": _deg(25), "bow": _mm(-200), "skew": 0.12,
      "window_width": _mm(1250), "window_height": _mm(1450),
      "window_center_height": 0.5, "waist_height": 0.48,
      "plate_diameter": _mm(700), "material_id": "stainless_316l_sheet"}),
    ("anthropic", 3, 34, "Compact 3.6 m loop with a stronger twist and a low "
     "waist",
     {"height": _mm(3600), "width": _mm(2400), "depth": _mm(800),
      "wall": _mm(6), "twist": _deg(35), "bow": _mm(100), "skew": 0.2,
      "window_width": _mm(950), "window_height": _mm(1100),
      "window_center_height": 0.45, "waist_height": 0.4,
      "plate_diameter": _mm(600), "material_id": "stainless_316l_sheet"}),
    ("openai", 3, 35, "Compact loop, slightly narrower, softer twist",
     {"height": _mm(3600), "width": _mm(2200), "depth": _mm(800),
      "wall": _mm(6), "twist": _deg(25), "bow": _mm(100), "skew": 0.15,
      "window_width": _mm(900), "window_height": _mm(1050),
      "window_center_height": 0.46, "waist_height": 0.42,
      "plate_diameter": _mm(600), "material_id": "stainless_316l_sheet"}),
]


def _height_width(params: dict) -> tuple[float, float]:
    def mm(d):
        return d["value"] * (1000.0 if d["unit"] == "m" else 1.0)
    return mm(params["height"]), mm(params["width"])


def lens_spec(provider: str, alt: int, seed: int, concept: str,
              params: dict) -> dict:
    from app.council.replay import canonical_spec_hash

    h, w = _height_width(params)
    spec = {
        "meta": {
            "spec_id": _id(f"spec-{provider}-{alt}"),
            "schema_version": "1.0.0",
            "project_id": PROJECT_ID,
            "seed": seed,
            "created_by": "DESIGNER",
            "provider": provider,
            "alternative_no": alt,
            "designdna_precedents": [],
        },
        "form_language": {
            "concept": concept,
            "cultural_basis": "organic void sculpture family (reference 08)",
            "silhouette": "freeform",
            "proportion_system": {
                "system": "custom", "ratio": round(h / w, 3),
                "notes": "height : width of the lens envelope",
            },
            "symmetry": "none",
        },
        "massing": {"elements": [{
            "element_id": "loop_01",
            "primitive": "freeform_loop",
            "parameters": copy.deepcopy(params),
            "material_id": "stainless_316l_sheet",
            "position": {"x_m": 0.0, "y_m": 0.0, "z_m": 0.0},
        }]},
        "materials": [{
            "material_id": "stainless_316l_sheet",
            "name": "316L stainless steel sheet",
            "category": "metal",
            "finish": "mirror polish",
        }],
        "water": {"has_water": False},
        "hydraulic_network": {"nodes": [], "edges": []},
        "site": {
            "climate_zone": "tropical_highland",
            "design_wind_m_per_s": 30.0,
            "frost_risk": False,
            "viewing_distance_m": 12.0,
        },
        "fabrication": {
            "method": "sheet_metal",
            "max_module_m": {"x": 5.0, "y": 5.0, "z": 5.0},
            "max_lift_kg": 3000.0,
            "local_capability_notes": (
                "Addis Ababa sheet shop, welded 316L; armature design and "
                "forming radius are fabricator inputs"),
        },
        "constraints": {
            "budget": {"amount": 6000000.0, "currency": "ETB",
                       "fx_date": "2026-09-09"},
            "hard_constraints": [
                "316L stainless sheet only",
                "no water on the sculpture itself",
                "single element; nothing stacks on the lens",
            ],
        },
        "confidence": 60,
        "assumptions": [
            {"statement": "Total assembly mass cannot be stated: the internal "
                          "armature is undesigned (FABRICATOR-INPUT-REQUIRED)",
             "sourced": True,
             "source": "registry declaration freeform_loop.INCOMPLETE_MASS_INPUTS"},
            {"statement": "The reflecting pool is site work outside this design",
             "sourced": True, "source": "client brief"},
            {"statement": "max_module_m 5 m per axis keeps the lens one module; "
                          "road transport of a piece this size is unconfirmed",
             "sourced": False},
        ],
    }
    spec["meta"]["spec_hash"] = "sha256:" + canonical_spec_hash(spec)
    return spec


# ---------------------------------------------------------------------------
# hand-authored responses
# ---------------------------------------------------------------------------

RESEARCH_PRIMARY = (
    "[synthetic researcher response — hand-authored, no provider called] "
    "Site: Addis Ababa, 2355 m altitude, tropical highland climate, no frost; "
    "an outdoor campus water court with a still reflecting pool that is site "
    "work. The client's reference family is the organic void sculpture "
    "(reference 08): one smooth asymmetrical loop with a single large "
    "through-opening and a changing, twisted cross-section. Material is fixed "
    "by the brief: welded 316L stainless sheet, mirror polished. The live "
    "registry offers exactly one primitive of this family, freeform_loop, "
    "which declares that its total mass is INCOMPLETE until the internal "
    "armature is designed and that it is PRE-FABRICATION only. No water on "
    "the sculpture, so no pump or nozzle envelope applies."
)
RESEARCH_PARALLEL = (
    "[synthetic researcher response — hand-authored, no provider called] "
    "Precedents: monumental polished stainless loops are installed on plinths "
    "or thin interface plates in reflecting pools; the reflecting pool here is "
    "outside the design. Constraints to carry: 316L sheet gauge is a nominal "
    "6 mm prototype value in the registry, the forming radius and the "
    "armature are fabricator inputs, and the piece is a single element."
)


def _geometrist_text(specs: list[dict]) -> str:
    lines = ["[synthetic geometrist notes — hand-authored, no provider called]"]
    for s in specs:
        p = s["massing"]["elements"][0]["parameters"]
        h, w = _height_width(p)
        lines.append(
            f"spec {s['meta']['spec_id']}: freeform_loop is in the live "
            f"registry; envelope {h:.0f} x {w:.0f} mm gives width/height "
            f"{w / h:.3f} inside the ref-08 band [0.48, 0.72]; wall "
            f"{p['wall']['value']} mm >= the 6 mm floor (3 mm embedment + "
            "3 mm ligament); single element, plate base. Buildable as a "
            "PRE-FABRICATION design; mass incomplete until the armature is "
            "designed."
        )
    return "\n".join(lines)


def _engineer_json(specs: list[dict], side: str) -> str:
    return json.dumps({
        "summary": (f"[synthetic engineering review ({side}) — hand-authored, "
                    "no provider called] Every candidate is a single 316L lens "
                    "whose total mass is not computable: the armature is "
                    "undesigned, so lift, overturning and bearing verdicts are "
                    "NEEDS INPUT by construction, not failures."),
        "per_spec": [{
            "spec_id": s["meta"]["spec_id"],
            "verdict": "pass_with_notes",
            "notes": (f"skin-only 316L at "
                      f"{s['massing']['elements'][0]['parameters']['wall']['value']} "
                      "mm is known geometry; armature mass, centroid and per-"
                      "module allocation are FABRICATOR-INPUT-REQUIRED; no "
                      "hydraulics (has_water false)."),
        } for s in specs],
    })


def _critic_json(specs: list[dict]) -> str:
    defects = []
    for i, s in enumerate(specs, 1):
        p = s["massing"]["elements"][0]["parameters"]
        defects.append({
            "id": f"D{i}", "severity": "major",
            "spec_id": s["meta"]["spec_id"],
            "defect": (f"Lift verdict impossible: total mass null (armature "
                       f"undesigned); the {p['wall']['value']} mm wall is a "
                       "nominal gauge, never verified; forming radius unresolved."),
        })
    defects.append({
        "id": f"D{len(specs) + 1}", "severity": "minor",
        "spec_id": specs[0]["meta"]["spec_id"],
        "defect": ("max_lift_kg 3000 is stated by the designer, not by the "
                   "workshop — it cannot bind until the mass exists."),
    })
    return json.dumps({"defects": defects})


def _arbiter_json(chosen: list[str]) -> str:
    return json.dumps({
        "chosen_spec_ids": chosen,
        "confidence": 0.7,
        "rationale": ("[synthetic arbiter decision — hand-authored, no provider "
                      "called] Rank 1 is the FF-A2 acceptance lens (the only "
                      "parameterization with a signed visual gate); ranks 2 "
                      "and 3 are distinct in-range variants. Every candidate "
                      "carries the same unresolved professional inputs."),
        "disagreement_register": [{
            "topic": "mass",
            "positions": {"engineer": "needs input by construction",
                          "critic": "major defect until the armature exists"},
            "resolution": "recorded; both are true — the design stays "
                          "PRE-FABRICATION",
        }],
        "stated_differences": {c: "distinct envelope/twist/window set"
                               for c in chosen},
    })


# ---------------------------------------------------------------------------

def compose_brief() -> tuple[str, dict]:
    """The session brief exactly as routes_council._compose_brief builds it
    for a confirmed intake (intake block, blank line, the stripped brief)."""
    from app.intake.models import IntakeV1, Sourced, summary_block

    intake_fx = json.loads(INTAKE_PATH.read_text(encoding="utf-8"))
    intake = IntakeV1()
    for dotted, value in intake_fx["fields"].items():
        section, name = dotted.split(".")
        setattr(getattr(intake, section), name,
                Sourced(value=value, source="operator"))
    # The route stores normalized_json and reloads it before composing —
    # round-trip through the SAME wire format so typed values take the
    # types the API gives them (an int altitude becomes 2355.0).
    intake = IntakeV1.model_validate(json.loads(json.dumps(intake.dump_wire())))
    block = summary_block(intake, intake_fx["intake_id_in_fixture"])
    return f"{block}\n\n{intake_fx['brief_text'].strip()}", intake_fx


def build_fixture() -> dict:
    import jsonschema

    from app.core.config import load_config_bundle
    from app.council import prompts
    from app.council.orchestrator import _validate_live_primitives

    bundle = load_config_bundle()
    roles = bundle.council.roles
    models = {p: bundle.council.model_defaults[p].text
              for p in ("anthropic", "openai", "kimi")}
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    schema_json = json.dumps(schema)   # exactly orchestrator._schema_json

    brief, _ = compose_brief()
    specs = [lens_spec(*v) for v in VARIANTS]
    for s in specs:
        jsonschema.validate(instance=s, schema=schema)
        problems = _validate_live_primitives(s)
        if problems:
            raise SystemExit(f"fixture spec {s['meta']['spec_id']} is not "
                             f"registry-valid: {problems}")

    calls: list[dict] = []

    def call(role, side, provider, prompt, response):
        calls.append({
            "id": _id(f"call-{len(calls)}-{role}-{side}"),
            "role": role, "side": side, "provider": provider,
            "model": models[provider], "ts": STARTED,
            "prompt": prompt, "response": response,
            "tokens_in": max(1, len(prompt) // 4),
            "tokens_out": max(1, len(response) // 4),
            "latency_ms": LATENCY_MS, "status": "ok",
        })

    # RESEARCHER (both sides, same prompt) — providers from council.yaml
    r_prompt = prompts.researcher_prompt(brief)
    call("researcher", "primary", roles["researcher"].primary, r_prompt,
         RESEARCH_PRIMARY)
    call("researcher", "parallel", roles["researcher"].parallel, r_prompt,
         RESEARCH_PARALLEL)
    research = RESEARCH_PRIMARY

    # DESIGNER x 3 alternatives x 2 providers — the orchestrator's order
    d_primary, d_parallel = roles["designer"].primary, roles["designer"].parallel
    by_key = {(v[0], v[1]): s for v, s in zip(VARIANTS, specs)}
    ordered_specs: list[dict] = []
    for alt in (1, 2, 3):
        for side, provider in (("primary", d_primary), ("parallel", d_parallel)):
            spec = by_key[(provider, alt)]
            call("designer", side, provider,
                 prompts.designer_prompt(brief, research, alt, schema_json),
                 json.dumps(spec))
            ordered_specs.append(spec)
    summary = prompts.candidates_summary(ordered_specs)

    # GEOMETRIST
    geo = _geometrist_text(ordered_specs)
    call("geometrist", "primary", roles["geometrist"].primary,
         prompts.geometrist_prompt(brief, summary), geo)
    call("geometrist", "parallel", roles["geometrist"].parallel,
         prompts.geometrist_prompt(brief, summary),
         geo.replace("[synthetic geometrist notes",
                     "[synthetic geometrist notes (parallel)"))

    # ENGINEER
    eng_prompt = prompts.engineer_prompt(brief, summary, geo)
    review_primary = _engineer_json(ordered_specs, "primary")
    call("engineer", "primary", roles["engineer"].primary, eng_prompt,
         review_primary)
    review_parallel = _engineer_json(ordered_specs, "parallel")
    call("engineer", "parallel", roles["engineer"].parallel, eng_prompt,
         review_parallel)

    # CRITIC — ADR-025 dynamic rule: never a producer; with the static
    # designer pair the only eligible provider is the one that designed
    # nothing. Derived here from the SAME rule, not typed.
    producers = {d_primary, d_parallel}
    eligible = [p for p in (roles["critic"].primary, roles["critic"].parallel,
                            "anthropic", "openai", "kimi")
                if p and p not in producers]
    critic_provider = eligible[0]
    crit_prompt = prompts.critic_prompt(brief, summary, review_primary)
    defects = _critic_json(ordered_specs)
    call("critic", "primary", critic_provider, crit_prompt, defects)

    # ARBITER
    chosen = [by_key[("anthropic", 1)]["meta"]["spec_id"],
              by_key[("openai", 2)]["meta"]["spec_id"],
              by_key[("anthropic", 3)]["meta"]["spec_id"]]
    arb_prompt = prompts.arbiter_prompt(brief, summary, review_primary, defects)
    call("arbiter", "primary", roles["arbiter"].primary, arb_prompt,
         _arbiter_json(chosen))
    call("arbiter", "parallel", roles["arbiter"].parallel, arb_prompt,
         json.dumps({"note": "[synthetic parallel arbiter concurrence — "
                             "hand-authored, no provider called]"}))

    return {
        "fixture_version": 1,
        "synthetic": True,
        "note": NOTE,
        "session": {
            "id": SESSION_ID,
            "brief_text": brief,
            "started_at": STARTED,
            "ended_at": ENDED,
            "degraded": 0,
            "corrected": 0,
        },
        "calls": calls,
        "design_specs": [{"spec": s} for s in ordered_specs],
        "engineering_reviews": [
            {"id": _id("review-primary"), "provider": roles["engineer"].primary,
             "side": "primary", "payload": json.loads(review_primary)},
            {"id": _id("review-parallel"), "provider": roles["engineer"].parallel,
             "side": "parallel", "payload": json.loads(review_parallel)},
        ],
        "defect_lists": [
            {"id": _id("defects-primary"), "provider": critic_provider,
             "side": "primary", "payload": json.loads(defects)},
        ],
        "arbiter_decision": {
            "id": _id("decision"),
            **{k: v for k, v in json.loads(_arbiter_json(chosen)).items()
               if k != "stated_differences"},
        },
    }


def dumps(fixture: dict) -> str:
    return json.dumps(fixture, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="regenerate in memory and compare with the committed "
                         "file; exit 1 on any drift")
    args = ap.parse_args(argv)
    fixture = build_fixture()
    text = dumps(fixture)
    if args.check:
        committed = FIXTURE_PATH.read_text(encoding="utf-8") \
            if FIXTURE_PATH.exists() else ""
        if committed == text:
            print(f"OK — {FIXTURE_PATH.name} matches the live prompt builders, "
                  f"schema and registry ({len(fixture['calls'])} calls, "
                  f"{len(fixture['design_specs'])} specs)")
            return 0
        print(f"DRIFT — {FIXTURE_PATH.name} no longer matches what the live "
              "builders produce; regenerate with scripts/make_ffa3_fixture.py")
        return 1
    FIXTURE_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {FIXTURE_PATH} ({len(text)} bytes, "
          f"{len(fixture['calls'])} calls, {len(fixture['design_specs'])} specs)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
